### ISSUE TITLE
Save a game

### ISSUE THREAD

**Issue by donkirkby** [donkirkby/zero-play#20]
It would be nice to be able to save a game to a text file, and load from that text file for later review.

Some ideas for formats:

### Plain Text
```
1. 1A 1B
X values: 1A: 0.8, 1B: -0.2
O values: 1C: 0.8, 1B: 0.3
2. 2B 2A
X values: 2B: 0.9, 3A: -0.9
O values: 2A: 0.9, 3A: -0.9
```

### Markdown
One benefit is that this format would be easy to include in a journal entry.

```
1. 1A 1B
   * X values: 1A: 0.8, 1B: -0.2
   * O values: 1C: 0.8, 1B: 0.3
2. 2B 2A
   * X values: 2B: 0.9, 3A: -0.9
   * O values: 2A: 0.9, 3A: -0.9
```

### YAML
```
- step: 1
  x:
    move: 1A
    values:
      - move: 1A
        value: 0.8
      - move: 1B
        value: -0.2
  o:
    move: 1B
    values:
      - move: 1C
        value: 0.8
      - move: 1B
        value: 0.3
```

### Other Ideas
* Maybe append ? for moves with significantly lower value than the best choice.
* Allow reanalysis of the moves in a game, and choose how many iterations to run, or just run a continuous analysis while displaying the number of iterations so far. Separate issue?
* Include other annotations, like the number of times each choice was explored?
